#!/bin/bash
# EveryStore Setup Wizard
# Generates a .env file by walking through all configuration options.

set -e

BOLD='\033[1m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
RESET='\033[0m'

title()   { echo -e "\n${BOLD}${CYAN}=== $1 ===${RESET}"; }
info()    { echo -e "${GREEN}✓${RESET} $1"; }
warn()    { echo -e "${YELLOW}! $1${RESET}"; }
ask()     { echo -e "${BOLD}$1${RESET}"; }

ask_input() {
    # ask_input "Prompt" "default_value" → stores in REPLY
    local prompt="$1"
    local default="$2"
    if [ -n "$default" ]; then
        read -rp "$(echo -e "${BOLD}${prompt}${RESET} [${default}]: ")" REPLY
        REPLY="${REPLY:-$default}"
    else
        read -rp "$(echo -e "${BOLD}${prompt}${RESET}: ")" REPLY
    fi
}

ask_secret() {
    # Like ask_input but hides input
    local prompt="$1"
    read -rsp "$(echo -e "${BOLD}${prompt}${RESET}: ")" REPLY
    echo
}

ask_choice() {
    # ask_choice "Prompt" "1" "opt1" "opt2" ...
    local prompt="$1"; local default="$2"; shift 2
    local opts=("$@")
    echo -e "${BOLD}${prompt}${RESET}"
    for i in "${!opts[@]}"; do
        echo "  $((i+1))) ${opts[$i]}"
    done
    while true; do
        read -rp "$(echo -e "Choose [${default}]: ")" REPLY
        REPLY="${REPLY:-$default}"
        if [[ "$REPLY" =~ ^[0-9]+$ ]] && [ "$REPLY" -ge 1 ] && [ "$REPLY" -le "${#opts[@]}" ]; then
            break
        fi
        echo -e "${RED}Invalid choice, enter a number 1–${#opts[@]}${RESET}"
    done
}

# ────────────────────────────────────────────
echo -e "${BOLD}${CYAN}"
echo "  ███████╗██╗   ██╗███████╗██████╗ ██╗   ██╗"
echo "  ██╔════╝██║   ██║██╔════╝██╔══██╗╚██╗ ██╔╝"
echo "  █████╗  ██║   ██║█████╗  ██████╔╝ ╚████╔╝ "
echo "  ██╔══╝  ╚██╗ ██╔╝██╔══╝  ██╔══██╗  ╚██╔╝  "
echo "  ███████╗ ╚████╔╝ ███████╗██║  ██║   ██║   "
echo "  ╚══════╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝   ╚═╝   "
echo -e "${RESET}"
echo -e "${BOLD}EveryStore Setup Wizard${RESET}"
echo "This script will create your .env file."
echo "Press Enter to accept the default value shown in [brackets]."

if [ -f .env ]; then
    warn ".env already exists. This will overwrite it."
    read -rp "Continue? (y/N): " CONFIRM
    [[ "$CONFIRM" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }
fi

OUT=".env"
> "$OUT"

cat >> "$OUT" <<'HEADER'
# ============================================================
#  EveryStore — Environment Configuration
#  Generated by setup.sh
#  NEVER commit this file to git.
# ============================================================

HEADER

# ────────────────────────────────────────────
title "Django Core"

# Secret key
ask_choice "Django SECRET_KEY" "1" \
    "Auto-generate a secure key (recommended)" \
    "Enter my own key"
if [ "$REPLY" = "1" ]; then
    SECRET_KEY=$(python3 -c "import secrets,string; print(''.join(secrets.choice(string.ascii_letters+string.digits+'!@#\$%^&*(-_=+)') for _ in range(60)))" 2>/dev/null \
        || openssl rand -base64 45 | tr -d '\n/+=')
    info "Secret key generated."
else
    ask_input "Enter SECRET_KEY"
    SECRET_KEY="$REPLY"
fi

ask_input "ALLOWED_HOSTS (your EC2 IP or domain, comma-separated)" "your-ec2-ip"
ALLOWED_HOSTS="$REPLY"

cat >> "$OUT" <<EOF
SECRET_KEY=$SECRET_KEY
DEBUG=False
ALLOWED_HOSTS=$ALLOWED_HOSTS

EOF

# ────────────────────────────────────────────
title "Database"

ask_choice "Database" "1" \
    "Bundled PostgreSQL container (easiest, no extra setup)" \
    "AWS RDS PostgreSQL (recommended for production)"

if [ "$REPLY" = "1" ]; then
    info "Using bundled PostgreSQL container."
    ask_secret "Database password (leave blank to auto-generate)"
    if [ -z "$REPLY" ]; then
        DB_PASS=$(openssl rand -hex 16)
        info "Password auto-generated."
    else
        DB_PASS="$REPLY"
    fi
    cat >> "$OUT" <<EOF
# ----- Database (bundled container) -----
DB_HOST=everystore-db
DB_PORT=5432
DB_NAME=everystore
DB_USER=everystore
DB_PASS=$DB_PASS
DB_SSLMODE=disable

EOF
else
    info "Using AWS RDS."
    ask_input "RDS endpoint" "mydb.abc123.us-east-1.rds.amazonaws.com"
    DB_HOST="$REPLY"
    ask_input "DB name" "everystore"
    DB_NAME="$REPLY"
    ask_input "DB user" "everystore"
    DB_USER="$REPLY"
    ask_secret "DB password"
    DB_PASS="$REPLY"
    cat >> "$OUT" <<EOF
# ----- Database (AWS RDS) -----
DB_HOST=$DB_HOST
DB_PORT=5432
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASS=$DB_PASS
DB_SSLMODE=require

EOF
fi

# ────────────────────────────────────────────
title "AWS S3 (Product Image Storage)"

ask_choice "Where to store product images?" "1" \
    "Local storage on this server (easiest)" \
    "AWS S3 (recommended — survives container restarts)"

if [ "$REPLY" = "1" ]; then
    info "Using local storage. Images will be stored on this server."
    cat >> "$OUT" <<'EOF'
# ----- AWS S3 (disabled — using local storage) -----
S3_BUCKET=
S3_REGION=
S3_ACCESS_KEY=
S3_SECRET_KEY=

EOF
else
    ask_input "S3 bucket name"
    S3_BUCKET="$REPLY"
    ask_input "S3 region" "us-east-1"
    S3_REGION="$REPLY"
    ask_input "IAM Access Key ID"
    S3_ACCESS_KEY="$REPLY"
    ask_secret "IAM Secret Access Key"
    S3_SECRET_KEY="$REPLY"
    cat >> "$OUT" <<EOF
# ----- AWS S3 -----
S3_BUCKET=$S3_BUCKET
S3_REGION=$S3_REGION
S3_ACCESS_KEY=$S3_ACCESS_KEY
S3_SECRET_KEY=$S3_SECRET_KEY

EOF
    warn "Make sure your S3 bucket has public read access enabled."
    warn "Bucket policy: Actions → s3:GetObject, Principal → *, Resource → arn:aws:s3:::${S3_BUCKET}/*"
fi

# ────────────────────────────────────────────
title "PayPal Payments"

ask_choice "Payment mode" "1" \
    "Sandbox / Testing (no real money)" \
    "Live (real payments)"

if [ "$REPLY" = "1" ]; then
    PAYMENT_MODE=sandbox
    warn "Sandbox mode: use your PayPal developer test credentials."
    warn "Get them at: https://developer.paypal.com/dashboard/applications/sandbox"
else
    PAYMENT_MODE=live
    warn "Live mode: real money will be charged."
    warn "Get your Live credentials at: https://developer.paypal.com/dashboard/applications/live"
fi

ask_input "PayPal Client ID"
PAYPAL_CLIENT_ID="$REPLY"
ask_secret "PayPal Client Secret"
PAYPAL_CLIENT_SECRET="$REPLY"

cat >> "$OUT" <<EOF
# ----- PayPal -----
PAYMENT_MODE=$PAYMENT_MODE
PAYPAL_CLIENT_ID=$PAYPAL_CLIENT_ID
PAYPAL_CLIENT_SECRET=$PAYPAL_CLIENT_SECRET

EOF

# ────────────────────────────────────────────
title "SSL / HTTPS"

ask_choice "SSL certificate" "1" \
    "Let's Encrypt — auto-obtain and auto-renew (requires a domain name)" \
    "Custom certificate — I have my own cert files" \
    "Self-signed — auto-generated (browser will show a warning)"

SSL_CHOICE="$REPLY"

if [ "$SSL_CHOICE" = "1" ]; then
    ask_input "Your domain name (e.g. store.example.com)"
    DOMAIN="$REPLY"
    ask_input "Email for Let's Encrypt notifications"
    CERTBOT_EMAIL="$REPLY"
    cat >> "$OUT" <<EOF
# ----- SSL (Let's Encrypt) -----
DOMAIN=$DOMAIN
CERTBOT_EMAIL=$CERTBOT_EMAIL
SSL_CERT_PATH=
SSL_KEY_PATH=

EOF
    info "Let's Encrypt cert will be obtained automatically on first run."
elif [ "$SSL_CHOICE" = "2" ]; then
    ask_input "Absolute path to your certificate file (e.g. /etc/ssl/certs/mycert.crt)"
    SSL_CERT_PATH="$REPLY"
    ask_input "Absolute path to your private key file (e.g. /etc/ssl/private/mykey.key)"
    SSL_KEY_PATH="$REPLY"
    cat >> "$OUT" <<EOF
# ----- SSL (Custom Certificate) -----
DOMAIN=
CERTBOT_EMAIL=
SSL_CERT_PATH=$SSL_CERT_PATH
SSL_KEY_PATH=$SSL_KEY_PATH

EOF
else
    info "Self-signed cert will be generated automatically."
    cat >> "$OUT" <<'EOF'
# ----- SSL (self-signed, auto-generated) -----
DOMAIN=
CERTBOT_EMAIL=
SSL_CERT_PATH=
SSL_KEY_PATH=

EOF
fi

# ────────────────────────────────────────────
title "Email (Order Confirmation Emails)"

ask_choice "Send order confirmation emails?" "1" \
    "Yes — configure SMTP" \
    "No — skip for now"

if [ "$REPLY" = "1" ]; then
    ask_choice "Email provider" "1" \
        "Gmail" \
        "Other SMTP"
    if [ "$REPLY" = "1" ]; then
        EMAIL_HOST=smtp.gmail.com
        EMAIL_PORT=465
        warn "Gmail: enable 2-Step Verification, then generate an App Password at:"
        warn "https://myaccount.google.com/apppasswords"
        ask_input "Your Gmail address"
        EMAIL_HOST_USER="$REPLY"
        ask_secret "Gmail App Password (no spaces)"
        EMAIL_HOST_PASSWORD="$REPLY"
        EMAIL_FROM="EveryStore <${EMAIL_HOST_USER}>"
    else
        ask_input "SMTP host"
        EMAIL_HOST="$REPLY"
        ask_input "SMTP port" "465"
        EMAIL_PORT="$REPLY"
        ask_input "SMTP username"
        EMAIL_HOST_USER="$REPLY"
        ask_secret "SMTP password"
        EMAIL_HOST_PASSWORD="$REPLY"
        ask_input "From address (e.g. Store Name <you@example.com>)"
        EMAIL_FROM="$REPLY"
    fi
    cat >> "$OUT" <<EOF
# ----- Email -----
EMAIL_HOST=$EMAIL_HOST
EMAIL_PORT=$EMAIL_PORT
EMAIL_HOST_USER=$EMAIL_HOST_USER
EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
EMAIL_FROM=$EMAIL_FROM

EOF
else
    info "Skipping email setup. Order confirmation emails will be disabled."
    cat >> "$OUT" <<'EOF'
# ----- Email (disabled) -----
EMAIL_HOST=
EMAIL_PORT=465
EMAIL_HOST_USER=
EMAIL_HOST_PASSWORD=
EMAIL_FROM=

EOF
fi

# ────────────────────────────────────────────
title "Store Settings"

ask_input "Store name" "EveryStore"
STORE_NAME="$REPLY"

ask_input "Currency code" "USD"
STORE_CURRENCY="$REPLY"

ask_choice "Seller contact type (shown on storefront)" "1" \
    "Email" \
    "WhatsApp" \
    "Telegram" \
    "WeChat" \
    "Discord"
case "$REPLY" in
    1) SELLER_CONTACT_TYPE=email ;;
    2) SELLER_CONTACT_TYPE=whatsapp ;;
    3) SELLER_CONTACT_TYPE=telegram ;;
    4) SELLER_CONTACT_TYPE=wechat ;;
    5) SELLER_CONTACT_TYPE=discord ;;
esac
ask_input "Contact value (e.g. your email address or username)"
SELLER_CONTACT_VALUE="$REPLY"

cat >> "$OUT" <<EOF
# ----- Store -----
STORE_NAME=$STORE_NAME
STORE_CURRENCY=$STORE_CURRENCY
SELLER_CONTACT_TYPE=$SELLER_CONTACT_TYPE
SELLER_CONTACT_VALUE=$SELLER_CONTACT_VALUE

EOF

# ────────────────────────────────────────────
title "Theme (Optional)"

ask_choice "Customize theme colors and logo?" "2" \
    "Yes" \
    "No — use defaults"

if [ "$REPLY" = "1" ]; then
    ask_input "Primary color (hex)" "#6366f1"
    THEME_PRIMARY_COLOR="$REPLY"
    ask_input "Logo URL (full URL, leave blank for text logo)"
    THEME_LOGO_URL="$REPLY"
    ask_input "Hero/banner image URL (leave blank for gradient)"
    THEME_HERO_IMAGE_URL="$REPLY"
else
    THEME_PRIMARY_COLOR="#6366f1"
    THEME_LOGO_URL=""
    THEME_HERO_IMAGE_URL=""
fi

cat >> "$OUT" <<EOF
# ----- Theme -----
THEME_PRIMARY_COLOR=$THEME_PRIMARY_COLOR
THEME_LOGO_URL=$THEME_HERO_IMAGE_URL
THEME_HERO_IMAGE_URL=$THEME_HERO_IMAGE_URL
EOF

# ────────────────────────────────────────────
echo -e "\n${BOLD}${GREEN}✓ Setup complete!${RESET}"
echo -e "Your .env file has been created. You can review it with: ${BOLD}cat .env${RESET}"
echo ""
echo -e "To start EveryStore:"
echo -e "  ${BOLD}docker compose up -d${RESET}"
echo ""
echo -e "To get admin credentials after first run:"
echo -e "  ${BOLD}docker compose logs everystore-app | grep -A3 'Admin credentials'${RESET}"
echo ""
